"""My Summer Projects
Author: Sagarika
Project: Guess the number
What is it? The program asks the user to guess the number randomly generated by the computer and
lets them know where they at."""

from random import randint


def get_input() -> int:
    """gets user input and returns only if it is an integer"""
    while True:
        try:
            user_input = int(input("Your guess please? (The number should be an integer between 1 and 20): "))
            return user_input
        except ValueError:
            print("Sorry Invalid Input. Enter an integer between 1 and 20")


def give_feedback(user_input: int, num: int) -> None:
    """Validates user input and provides feedback"""
    while user_input != num:
        if 0 < user_input < 21:
            if user_input < num:
                print("The number you entered is too low.")
                user_input = get_input()
            else:
                print("The number you entered is too high.")
                user_input = get_input()
        else:
            print("The number should be between 1 and 20")
            user_input = get_input()

    print("You got it!!!")


def main():
    num_to_guess = randint(0, 20)
    user_input = get_input()
    give_feedback(user_input, num_to_guess)


main()
